spring:
  redis:
    host: 10.211.55.5
    port: 3379
    password:
    database: 0
    ssl: false
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000

blade:
  datasource:
    prod:
      url: jdbc:mysql://192.168.1.107:3306/blade?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: ejiang-cloud
      password: P@ssw02d!
